name: Daily build

# Controls when the action will run.
on: 
  schedule:
    - cron: '30 2 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    build:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v2

            # Set up Java Environment
            - name: Set up JDK 11
              uses: actions/setup-java@v1
              with:
                java-version: 11        
            
            # Build the ballerina project
            - name: Ballerina Build
              uses: ballerina-platform/ballerina-action@nightly
              with:
                  args:
                      build -c
              env:
                JAVA_HOME: /usr/lib/jvm/default-jvm

            # Send notification when build fails
            - name: Notify failure
              if: ${{ failure() }}
              run: |
                curl \
                -X POST 'https://chat.googleapis.com/v1/spaces/${{secrets.BALLERINA_CHAT_ID}}/messages?key=${{secrets.BALLERINA_CHAT_KEY}}&token=${{secrets.BALLERINA_CHAT_TOKEN}}' \
                --header 'Content-Type: application/json' \
                -d '{"text": "*module-ballerinax-snowflake.driver* daily build failure \nPlease visit <https://github.com/ballerina-platform/module-ballerinax-snowflake.driver/actions?query=workflow%3A%22Daily+build%22|the daily build page> for more information"}'

                curl \
                -X POST 'https://chat.googleapis.com/v1/spaces/${{secrets.CONNECTOR_CHAT_ID}}/messages?key=${{secrets.CONNECTOR_CHAT_KEY}}&token=${{secrets.CONNECTOR_CHAT_TOKEN}}' \
                --header 'Content-Type: application/json' \
                -d '{"text": "*module-ballerinax-snowflake.driver* daily build failure \nPlease visit <https://github.com/ballerina-platform/module-ballerinax-snowflake.driver/actions?query=workflow%3A%22Daily+build%22|the daily build page> for more information"}'
